name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]


env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    # 增加可用磁盘空间
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:

        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        # 如果空间还是不够用，可以把以下开启，清理出更多空间
        # remove-android: 'true'
        # remove-codeql: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

# 4. 构建并推送 Dify API
    - name: Build and Push Dify API
      uses: docker/build-push-action@v5
      with:
          context: .
          file: ./api/Dockerfile
          push: true
          tags: ${{ secrets.ALIYUN_REGISTRY }}/dify/dify-api:latest

      # 5. 构建并推送 Dify Web
    - name: Build and Push Dify Web
      uses: docker/build-push-action@v5
      with:
          context: .
          file: ./web/Dockerfile
          push: true
          tags: ${{ secrets.ALIYUN_REGISTRY }}/dify/dify-web:latest

      # 6. 构建并推送 Dify Worker
    - name: Build and Push Dify Worker
      uses: docker/build-push-action@v5
      with:
          context: .
          file: ./api/Dockerfile
          push: true
          tags: ${{ secrets.ALIYUN_REGISTRY }}/dify/dify-worker:latest
          target: worker

      # 7. 构建并推送 Dify Sandbox
    - name: Build and Push Dify Sandbox
      uses: docker/build-push-action@v5
      with:
          context: .
          file: ./api/Dockerfile
          push: true
          tags: ${{ secrets.ALIYUN_REGISTRY }}/dify/dify-sandbox:latest
          target: sandbox
